---
id: tokyork12
base_name: scenario
tags:
  - ruby
presentation_date: "2025-01-17"
tags: []
version: 1.0.0
licenses: []
author:
  markup_language: md
  name: makicamel
  email: unright@gmail.com
  rubygems_user: makicamel
  source_code_uri: "https://github.com/makicamel/tokyork12"
